### ISSUE TITLE
elm-format crashes

### ISSUE THREAD

**Issue by ImmaculatePine** [elm-community/SublimeElmLanguageSupport#60]
I'm using Elm 0.19 with this plugin and today it started to throw some Python errors when I run "Run elm-format" command:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/aleksandrborovykh/Library/Application Support/Sublime Text 3/Installed Packages/Elm Language Support.sublime-package/elm_format.py", line 27, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1386, in _execute_child
TypeError: Can't convert 'NoneType' object to str implicitly
```

Everything was perfect yesterday.

I have already tried to install just this plugin on a clean Sublime setup but got the same behaviour.

**Comment by sentience** [comment]
@ImmaculatePine How odd. I'm not sure how the old package could have been working with Elm 0.19 at all. Oh well!
