### ISSUE TITLE
Elm format not working "no such file or directory"

### ISSUE THREAD

**Issue by kottkrig** [elm-community/SublimeElmLanguageSupport#64]
Operating system: macOS 10.14.2
Sublime Text version: 3.1.1
Elm: 0.19.0
Elm-format: 0.8.1

I have both `elm` and `elm-format` installed and they are both available in my path. I have no trouble running them in my terminal.

Are there any obvious steps that are missing from the instructions in the readme? I'm getting the following error in the ST console whenever I run `elm-format`:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/johan/Library/Application Support/Sublime Text 3/Installed Packages/Elm Language Support.sublime-package/elm_format.py", line 27, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'elm-format'
```

**Comment by kottkrig** [comment]
I've also tried to override the `elm_paths` setting in `Elm Language Support.sublime-settings`:

```
{
  "elm_paths": "/usr/local/bin/elm-format"
}
```
